IdentitySample/ViewModels/ManageUser/AddOrRemoveClaimViewModel.cs
using System.Collections.Generic;

namespace IdentitySample.ViewModels.ManageUser
{
    public class AddOrRemoveClaimViewModel
    {
        public AddOrRemoveClaimViewModel()
        {
            UserClaims = new List<ClaimsViewModel>();
        }

        public AddOrRemoveClaimViewModel(string userId, IList<ClaimsViewModel> userClaims)
        {
            UserId = userId;
            UserClaims = userClaims;
        }
        
        public string UserId { get; set; }
        public IList<ClaimsViewModel> UserClaims { get; set; }
    }
}

IdentitySample/ViewModels/ManageUser/AddUserToRoleViewModel.cs
using System.Collections.Generic;

namespace IdentitySample.ViewModels.ManageUser
{
    public class AddUserToRoleViewModel
    {
        public AddUserToRoleViewModel()
        {
            UserRoles = new List<UserRolesViewModel>();
        }

        public AddUserToRoleViewModel(string userId, List<UserRolesViewModel> userRoles)
        {
            UserId = userId;
            UserRoles = userRoles;
        }

        public string UserId { get; set; }

        public List<UserRolesViewModel> UserRoles { get; set; }
    }
}

IdentitySample/ViewModels/ManageUser/ClaimsViewModel.cs
namespace IdentitySample.ViewModels.ManageUser
{
    public class ClaimsViewModel
    {
        
        public ClaimsViewModel()
        {
        }

        public ClaimsViewModel(string claimType)
        {
            ClaimType = claimType;
        }

        public string ClaimType { get; set; }
        public bool IsSelected { get; set; }
    }
}

IdentitySample/ViewModels/ManageUser/IndexViewModel.cs
namespace IdentitySample.ViewModels.ManageUser
{
    public class IndexViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    }
}

IdentitySample/ViewModels/ManageUser/UserRolesViewModel.cs
namespace IdentitySample.ViewModels.ManageUser
{
    public class UserRolesViewModel
    {
        public UserRolesViewModel()
        {
        }

        public UserRolesViewModel(string roleName)
        {
            RoleName = roleName;
        }

        public string RoleName { get; set; }

        public bool IsSelected { get; set; }
    }
}

IdentitySample/Controllers/ManageUserController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IdentitySample.Repositories;
using IdentitySample.ViewModels.ManageUser;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IdentitySample.Controllers
{
    public class ManageUserController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public ManageUserController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _userManager.Users
                .Select(u => new IndexViewModel()
                { Id = u.Id, UserName = u.UserName, Email = u.Email }).ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(string id, string userName)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(userName)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            user.UserName = userName;
            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.AsTracking()
                .Select(r => r.Name).ToList();
            var userRoles = await _userManager.GetRolesAsync(user);
            var validRoles = roles.Where(r => !userRoles.Contains(r))
                .Select(r => new UserRolesViewModel(r)).ToList();
            var model = new AddUserToRoleViewModel(id, validRoles);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.AddToRolesAsync(user, requestRoles);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserFromRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            var userRoles = await _userManager.GetRolesAsync(user);
            var validRoles = userRoles.Select(r => new UserRolesViewModel(r)).ToList();
            var model = new AddUserToRoleViewModel(id, validRoles);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserFromRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.RemoveFromRolesAsync(user, requestRoles);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddUserToClaim(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var allClaim = ClaimStore.AllClaims;
            var userClaims = await _userManager.GetClaimsAsync(user);
            var validClaims =
                allClaim.Where(c => userClaims.All(x => x.Type != c.Type))
                    .Select(c => new ClaimsViewModel(c.Type)).ToList();

            var model = new AddOrRemoveClaimViewModel(id, validClaims);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToClaim(AddOrRemoveClaimViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestClaims =
                model.UserClaims.Where(r => r.IsSelected)
                .Select(u => new Claim(u.ClaimType, true.ToString())).ToList();

            var result = await _userManager.AddClaimsAsync(user, requestClaims);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserFromClaim(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            var userClaims = await _userManager.GetClaimsAsync(user);
            var validClaims =
                userClaims.Select(c => new ClaimsViewModel(c.Type)).ToList();

            var model = new AddOrRemoveClaimViewModel(id, validClaims);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserFromClaim(AddOrRemoveClaimViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestClaims =
                model.UserClaims.Where(r => r.IsSelected)
                    .Select(u => new Claim(u.ClaimType, true.ToString())).ToList();

            var result = await _userManager.RemoveClaimsAsync(user, requestClaims);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
    }
}

IdentitySample/Views/ManageUser/AddUserToClaim.cshtml
@model IdentitySample.ViewModels.ManageUser.AddOrRemoveClaimViewModel
@{
    ViewData["Title"] = "AddUserToClaim";
}

<h1>AddUserToClaim</h1>

@if (!Model.UserClaims.Any())
{
    <h1>یافت نشد "Claim" هیج</h1>
}
else
{
    <form asp-controller="ManageUser" asp-action="AddUserToClaim" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        @for (int i = 0; i < Model.UserClaims.Count; i++)
        {
            <div class="form-group">
                <input asp-for="@Model.UserClaims[i].IsSelected" />
                <label>@Model.UserClaims[i].ClaimType</label>

                <input type="hidden" asp-for="@Model.UserClaims[i].ClaimType" />
            </div>
        }
        <input type="hidden" asp-for="@Model.UserId" />
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
}

IdentitySample/Views/ManageUser/AddUserToRole.cshtml
@model IdentitySample.ViewModels.ManageUser.AddUserToRoleViewModel
@{
    ViewData["Title"] = "AddUserToRole";
}

<h1>AddUserToRole</h1>


@if (!Model.UserRoles.Any())
{
    <h1>هیچ مقامی یافت نشد</h1>
}
else
{
    <form asp-controller="ManageUser" asp-action="AddUserToRole" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        @for (int i = 0; i < Model.UserRoles.Count; i++)
        {
            <div class="form-group">
                <input asp-for="@Model.UserRoles[i].IsSelected" />
                <label>@Model.UserRoles[i].RoleName</label>

                <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
            </div>
        }
        <input type="hidden" asp-for="@Model.UserId" />
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
}

IdentitySample/Views/ManageUser/EditUser.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser
@{
    ViewData["Title"] = "EditUser";
}

<h1>EditUser</h1>

<form asp-controller="ManageUser" asp-action="EditUser" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label class="control-label" asp-for="UserName"></label>
        <input class="form-control" asp-for="UserName" />
    </div>

    <input type="hidden" asp-for="Id" />

    <button class="btn btn-primary" type="submit">Submit</button>
</form>

IdentitySample/Views/ManageUser/Index.cshtml
@model List<IdentitySample.ViewModels.ManageUser.IndexViewModel>
@{
    ViewData["Title"] = "Index";
}


@if (!Model.Any())
{
    <h1>کاربری یافت نشد</h1>
}
else
{
    for (int i = 0; i < Model.Count; i++)
    {
        <div class="card mt-2">
            <div class="card-header">
                User Name : <b>@Model[i].UserName</b>
            </div>
            <div class="card-body">
                User Email : <b>@Model[i].Email</b>
            </div>
            <div class="card-footer">
                <form asp-controller="ManageUser" asp-action="DeleteUser" asp-route-id="@Model[i].Id" method="post">

                    <a asp-controller="ManageUser" asp-action="EditUser" asp-route-id="@Model[i].Id"
                       class="btn btn-primary">Edit Username</a>

                    <a asp-controller="ManageUser" asp-action="AddUserToRole" asp-route-id="@Model[i].Id"
                       class="btn btn-primary">Add to role</a>
                    <a asp-controller="ManageUser" asp-action="RemoveUserFromRole" asp-route-id="@Model[i].Id"
                       class="btn btn-danger">Remove From role</a>
                    <br />
                    <br />
                    <a asp-controller="ManageUser" asp-action="AddUserToClaim" asp-route-id="@Model[i].Id"
                       class="btn btn-primary">Add to Claim</a>
                    <a asp-controller="ManageUser" asp-action="RemoveUserFromClaim" asp-route-id="@Model[i].Id"
                       class="btn btn-danger">Remove From Claim</a>


                    <button type="submit" class="btn btn-danger">Delete user</button>
                </form>
            </div>
        </div>
    }
}

IdentitySample/Views/ManageUser/RemoveUserFromClaim.cshtml
@model IdentitySample.ViewModels.ManageUser.AddOrRemoveClaimViewModel

@{
    ViewData["Title"] = "RemoveUserFromClaim";
}

<h1>RemoveUserFromClaim</h1>

@if (!Model.UserClaims.Any())
{
    <h1>یافت نشد "Claim" هیج</h1>
}
else
{
    <form asp-controller="ManageUser" asp-action="RemoveUserFromClaim" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        @for (int i = 0; i < Model.UserClaims.Count; i++)
        {
            <div class="form-group">
                <input asp-for="@Model.UserClaims[i].IsSelected" />
                <label>@Model.UserClaims[i].ClaimType</label>

                <input type="hidden" asp-for="@Model.UserClaims[i].ClaimType" />
            </div>
        }

        <input type="hidden" asp-for="@Model.UserId" />
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
}

IdentitySample/Views/ManageUser/RemoveUserFromRole.cshtml
@model IdentitySample.ViewModels.ManageUser.AddUserToRoleViewModel
@{
    ViewData["Title"] = "DeleteUserToRole";
}

<h1>DeleteUserToRole</h1>

<form asp-controller="ManageUser" asp-action="RemoveUserFromRole" method="post">
    <div asp-validation-summary="ModelOnly"></div>
    @if (!Model.UserRoles.Any())
    {
        <h1>هیچ مقامی یافت نشد</h1>
    }
    else
    {
        for (int i = 0; i < Model.UserRoles.Count; i++)
        {
            <div class="form-group">
                <input asp-for="@Model.UserRoles[i].IsSelected" />
                <label>@Model.UserRoles[i].RoleName</label>

                <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
            </div>
        }
    }

    <input type="hidden" asp-for="@Model.UserId" />
    <button class="btn btn-primary" type="submit">Submit</button>
</form>